"""
Django settings for LordsonBackend project.

Generated by 'django-admin startproject' using Django 4.2.16.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # ✅ Add this

# Load environment variables
load_dotenv()
# -----------------------------------------------------------
# BASE CONFIGURATION
# -----------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-)ee%sgx0*e_tbp*1+_#9*!h#c4m%t2@v2%e^_b5_7*g$l1)8d-'

DEBUG = True

ALLOWED_HOSTS = []  # add ['*'] if you want to test on mobile via local network


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # your Vite frontend
    "http://127.0.0.1:5173",
]


# -----------------------------------------------------------
# APPLICATIONS
# -----------------------------------------------------------

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lordsonApp',
    'corsheaders',
    'rest_framework',
]

# -----------------------------------------------------------
# MIDDLEWARE
# -----------------------------------------------------------

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------------------------------
# URL & WSGI
# -----------------------------------------------------------

ROOT_URLCONF = 'LordsonBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # you can add your template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LordsonBackend.wsgi.application'

# -----------------------------------------------------------
# DATABASE (SQLite for local development)
# -----------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # 👈 Set to your timezone (India)
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------
# STATIC & MEDIA FILES
# -----------------------------------------------------------

# Static files (CSS, JS)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (uploads like banner images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -----------------------------------------------------------
# REST FRAMEWORK CONFIG (for API)
# -----------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # open access for now
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # DRF web UI
    ],
}

# -----------------------------------------------------------
# DEFAULT FIELD TYPE
# -----------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_test_yourKeyID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "yourSecretKey")