# Generated by Django 4.2.16 on 2025-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lordsonApp', '0002_remove_banner_link_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('sweatshirt', 'Sweatshirt')], max_length=20)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
