# Generated by Django 4.2.16 on 2025-11-18 21:18

import LordsonBackend.imagekit_storage
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('lordsonApp', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(storage=functools.partial(LordsonBackend.imagekit_storage.ImageKitStorage, *(), **{}), upload_to=''),
        ),
    ]
